### ISSUE TITLE
support for cqueues

### ISSUE THREAD

**Issue by fabled** [xs-embedded-llc/l2dbus#8]
I'm looking into using lua + dbus on project using heavily cqueues [1]. I'm wondering how big effort it would be to support cqueues as a main loop? Any pointers or documentation how to achieve this integration?

[1] https://github.com/wahern/cqueues

**Comment by gschmottlach** [comment]
Sorry, but I don't know enough about cqueues and how it's internally implemented to give you a good answer here. Originally I envisioned supporting a number of main-loop back-ends (libev and glib already being supported) and I thought about a Lua main-loop but never had time for the implementation. Part of the problem is that the main-loop is used by CDBUS so you might have to call out from C into Lua (cqueues) to do the scheduling. Add coroutines to the mix and it could get a little hairy. 

It's been a while since I dived deeply into the code so I've likely forgotten a fair amount of the implementation details. I'd encourage you to study the provided main-loop implementations . . . perhaps that might guide a cqueues implementation.
